<?php
declare(strict_types=1);
use Briefing\Store;
use Minishlink\WebPush\Subscription;
use Minishlink\WebPush\WebPush;
ini_set('display_errors','0');
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store, private');
header('X-Content-Type-Options: nosniff');
function reply(array $v,int $status=200):never{http_response_code($status);echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function allowed():bool{$ips=['62.109.128.59','212.57.32.9','62.109.150.10','212.57.32.162'];$ip=$_SERVER['REMOTE_ADDR']??'';if(in_array($ip,$ips,true))return true;$expected=getenv('BRIEFING_EMERGENCY_TOKEN')?:'';$given=(string)($_GET['token']??'');return $expected!==''&&$given!==''&&hash_equals($expected,$given);}
function impactRank(string $v):int{return ['not_affected'=>0,'watch'=>1,'affected'=>2][$v]??0;}
function validImpact(string $v):bool{return in_array($v,['affected','watch','not_affected'],true);}
function fingerprint(array $a):string{return hash('sha256',json_encode([$a['severity']??'',$a['category']??'',$a['title']??'',$a['summary']??'',$a['issuedAt']??'',$a['location']??null,$a['itineraryImpact']??null],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));}
function gemini(string $key,array $alert,array $itinerary):?array{
  if($key==='')return null;
  $stops=array_map(fn($s)=>['id'=>$s['id']??'','name'=>$s['name']??'','prefecture'=>$s['prefecture']??'','stay'=>$s['stayLabel']??'','highlights'=>array_column($s['routeHighlights']??[],'name')],$itinerary['trip']['stops']??[]);
  $prompt="Jsi bezpečnostní asistent pro konkrétní cestu po Japonsku. Vycházej POUZE z oficiální události a itineráře níže. Nezlehčuj ani nepřepisuj oficiální JMA instrukce, nevymýšlej další fakta. Vrať jediný JSON objekt s klíči summaryCz, actionCz, impactStatus (affected|watch|not_affected), affectedStopIds (pole ID), confidence (high|medium|low). summaryCz: max 2 krátké věty česky, co se stalo. actionCz: max 2 praktické věty pro cestovatele; pokud není třeba akce, řekni to. affected znamená přímý geografický/časový dopad na zastávku, trasu nebo výlet; watch realistickou možnost budoucího dopadu; not_affected mimo trasu/termín. Kritické oficiální instrukce mají vždy prioritu.\nUDÁLOST:\n".json_encode($alert,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\nITINERÁŘ:\n".json_encode($stops,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
  $body=['contents'=>[['role'=>'user','parts'=>[['text'=>$prompt]]]],'generationConfig'=>['temperature'=>0.1,'maxOutputTokens'=>600,'responseMimeType'=>'application/json']];
  $ch=curl_init('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:generateContent');
  curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>20,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>['Content-Type: application/json','x-goog-api-key: '.$key],CURLOPT_POSTFIELDS=>json_encode($body,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2,CURLOPT_PROTOCOLS=>CURLPROTO_HTTPS]);
  $raw=curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);if(!is_string($raw)||$code!==200)return null;
  $resp=json_decode($raw,true);$text=$resp['candidates'][0]['content']['parts'][0]['text']??null;if(!is_string($text))return null;$ai=json_decode($text,true);if(!is_array($ai)||!validImpact((string)($ai['impactStatus']??'')))return null;
  $known=array_column($itinerary['trip']['stops']??[],'id');$ids=array_values(array_intersect(array_map('strval',$ai['affectedStopIds']??[]),$known));
  return ['summaryCz'=>mb_substr(trim((string)($ai['summaryCz']??'')),0,900),'actionCz'=>mb_substr(trim((string)($ai['actionCz']??'')),0,900),'impactStatus'=>$ai['impactStatus'],'affectedStopIds'=>$ids,'confidence'=>in_array($ai['confidence']??'',['high','medium','low'],true)?$ai['confidence']:'low','model'=>'gemini-3.8-flash'];
}
function mergeAi(array $alert,?array $ai):array{
  if(!$ai)return $alert;$official=$alert['itineraryImpact']??['status'=>'not_affected','text'=>'','affectedStopIds'=>[]];$status=impactRank($ai['impactStatus'])>impactRank((string)($official['status']??''))?$ai['impactStatus']:(string)($official['status']??'not_affected');$ids=array_values(array_unique(array_merge($official['affectedStopIds']??[],$ai['affectedStopIds']??[])));$alert['itineraryImpact']['status']=$status;$alert['itineraryImpact']['affectedStopIds']=$ids;$alert['ai']=$ai;return $alert;
}
function shouldAi(array $a):bool{$sev=$a['severity']??'info';$impact=$a['itineraryImpact']['status']??'not_affected';return $sev==='critical'||$impact==='affected'||$impact==='watch';}
function shouldPush(array $a):bool{$sev=$a['severity']??'info';$impact=$a['itineraryImpact']['status']??'not_affected';if($sev==='critical')return true;if($sev==='warning')return in_array($impact,['affected','watch'],true);if($sev==='advisory')return $impact==='affected';return false;}
function pushAll(Store $s,array $config,array $alert):array{
  if(!class_exists(WebPush::class)||empty($config['vapid']['publicKey'])||empty($config['vapid']['privateKey']))return ['sent'=>0,'failed'=>0,'available'=>false];
  $impact=['affected'=>'ITINERÁŘ DOTČEN','watch'=>'ITINERÁŘ SLEDOVAT','not_affected'=>'ITINERÁŘ NEDOTČEN'][$alert['itineraryImpact']['status']??'not_affected']??'ITINERÁŘ';$title=($alert['severity']==='critical'?'🚨':'⚠️').' Japonsko: '.mb_substr((string)($alert['title']??'Nouzová informace'),0,90);$body=trim(($alert['ai']['summaryCz']??$alert['summary']??'').' '.$impact.'. '.($alert['ai']['actionCz']??''));$body=mb_substr($body,0,360);$payload=json_encode(['title'=>$title,'body'=>$body,'tag'=>'japan-'.substr(hash('sha256',(string)($alert['id']??$title)),0,24),'url'=>'./#japonsko'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
  $auth=['VAPID'=>['subject'=>$config['vapid']['subject']??($config['origin']??'https://briefing.nacestach.online'),'publicKey'=>$config['vapid']['publicKey'],'privateKey'=>$config['vapid']['privateKey']]];$ttl=$alert['severity']==='critical'?86400:21600;$urgency=$alert['severity']==='critical'?'high':'normal';$wp=new WebPush($auth,['TTL'=>$ttl,'urgency'=>$urgency,'batchSize'=>20,'contentType'=>'application/json']);$wp->setReuseVAPIDHeaders(true);$ids=[];
  foreach($s->query('SELECT id,value FROM subscriptions')->fetchAll() as $row){try{$raw=$s->unseal($row['value']);$wp->queueNotification(Subscription::create($raw),$payload);$ids[(string)$row['id']]=true;}catch(Throwable $e){}}
  $sent=0;$failed=0;foreach($wp->flush() as $report){$endpoint=$report->getRequest()->getUri()->__toString();$id=hash('sha256',$endpoint);if($report->isSuccess())$sent++;else{$failed++;if(method_exists($report,'isSubscriptionExpired')&&$report->isSubscriptionExpired())$s->query('DELETE FROM subscriptions WHERE id=?',[$id]);}}
  return ['sent'=>$sent,'failed'=>$failed,'available'=>true];
}
if(($_SERVER['REQUEST_METHOD']??'GET')!=='GET')reply(['error'=>'GET only'],405);if(!allowed())reply(['error'=>'Forbidden'],403);
try{
  $configPath=getenv('BRIEFING_CONFIG') ?: (is_file(__DIR__.'/config-path.php') ? require __DIR__.'/config-path.php' : dirname(__DIR__,2).'/private/config.php');if(!is_file($configPath))reply(['error'=>'Private config missing'],503);$config=require $configPath;require_once $config['serverDir'].'/core.php';$vendor=$config['serverDir'].'/vendor/autoload.php';if(is_file($vendor))require_once $vendor;$s=new Store($config);
  $public=dirname(__DIR__);$currentPath=$public.'/data/emergency-current.json';$itineraryPath=$public.'/data/japan-itinerary.json';if(!is_file($currentPath)||!is_file($itineraryPath))reply(['error'=>'Emergency data missing'],503);$current=json_decode((string)file_get_contents($currentPath),true,64,JSON_THROW_ON_ERROR);$itinerary=json_decode((string)file_get_contents($itineraryPath),true,64,JSON_THROW_ON_ERROR);
  $stateRaw=$s->query("SELECT value FROM meta WHERE id='emergencyDispatchState'")->fetchColumn();$state=is_string($stateRaw)?json_decode($stateRaw,true):[];if(!is_array($state))$state=[];$events=$state['events']??[];$settings=$s->settings();$aiKey=(string)($settings['apiKey']??'');$changed=0;$aiCalls=0;$pushes=0;$pushFailed=0;$newEvents=[];
  foreach($current['alerts']??[] as &$alert){$id=(string)($alert['id']??'');if($id==='')continue;$fp=fingerprint($alert);$old=$events[$id]??[];if(($old['fingerprint']??'')===$fp&&is_array($old['ai']??null))$alert=mergeAi($alert,$old['ai']);$isChanged=($old['fingerprint']??'')!==$fp;if($isChanged){$changed++;$ai=null;if($aiKey!==''&&shouldAi($alert)){$ai=gemini($aiKey,$alert,$itinerary);$aiCalls++;}$alert=mergeAi($alert,$ai);$pushResult=['sent'=>0,'failed'=>0,'available'=>false];if(shouldPush($alert)&&($old['notifiedFingerprint']??'')!==$fp){$pushResult=pushAll($s,$config,$alert);$pushes+=$pushResult['sent'];$pushFailed+=$pushResult['failed'];}$events[$id]=['fingerprint'=>$fp,'notifiedFingerprint'=>shouldPush($alert)?$fp:($old['notifiedFingerprint']??null),'ai'=>$alert['ai']??($old['ai']??null),'seenAt'=>gmdate(DATE_ATOM)];}else{$events[$id]=$old?:['fingerprint'=>$fp,'seenAt'=>gmdate(DATE_ATOM)];}$newEvents[$id]=$events[$id];}unset($alert);
  uasort($events,fn($a,$b)=>strcmp((string)($b['seenAt']??''),(string)($a['seenAt']??'')));$events=array_slice($events,0,250,true);$state=['updatedAt'=>gmdate(DATE_ATOM),'events'=>$events];$s->query('INSERT OR REPLACE INTO meta VALUES(?,?)',['emergencyDispatchState',json_encode($state,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);
  $current['dispatch']=['processedAt'=>(new DateTimeImmutable('now',new DateTimeZone('Asia/Tokyo')))->format(DATE_ATOM),'changed'=>$changed,'aiCalls'=>$aiCalls,'pushSent'=>$pushes,'pushFailed'=>$pushFailed,'aiEnabled'=>$aiKey!==''];$tmp=$currentPath.'.dispatch.'.bin2hex(random_bytes(4));$encoded=json_encode($current,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT);if(file_put_contents($tmp,$encoded,LOCK_EX)===false||!rename($tmp,$currentPath)){@unlink($tmp);reply(['error'=>'write failed'],500);}reply(['ok'=>true,'changed'=>$changed,'aiCalls'=>$aiCalls,'pushSent'=>$pushes,'pushFailed'=>$pushFailed,'aiEnabled'=>$aiKey!=='']);
}catch(Throwable $e){reply(['error'=>'Emergency dispatch failed'],500);}
