<?php
declare(strict_types=1);
ini_set('display_errors','0');
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store, private');
header('X-Content-Type-Options: nosniff');
const JMA_FEEDS=['随時'=>'https://www.data.jma.go.jp/developer/xml/feed/extra.xml','地震火山'=>'https://www.data.jma.go.jp/developer/xml/feed/eqvol.xml','その他'=>'https://www.data.jma.go.jp/developer/xml/feed/other.xml'];
const FDMA_RSS='https://www.fdma.go.jp/disaster/info/index.xml';
const JCG_RSS='https://www6.kaiho.mlit.go.jp/rss_en.xml';
const MAX_BYTES=2000000;const MAX_JMA_MESSAGES=45;
function out(array $v,int $status=200):never{http_response_code($status);echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT);exit;}
function allowed():bool{$ips=['62.109.128.59','212.57.32.9','62.109.150.10','212.57.32.162'];$ip=$_SERVER['REMOTE_ADDR']??'';if(in_array($ip,$ips,true))return true;$expected=getenv('BRIEFING_EMERGENCY_TOKEN')?:'';$given=(string)($_GET['token']??'');return $expected!==''&&$given!==''&&hash_equals($expected,$given);}
if(($_SERVER['REQUEST_METHOD']??'GET')!=='GET')out(['error'=>'GET only'],405);if(!allowed())out(['error'=>'Forbidden'],403);
function fetchUrl(string $url):string{$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>12,CURLOPT_USERAGENT=>'HonzaBriefingEmergency/1.0 (+https://briefing.nacestach.online/)',CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2,CURLOPT_PROTOCOLS=>CURLPROTO_HTTPS,CURLOPT_MAXFILESIZE=>MAX_BYTES]);$body=curl_exec($ch);$code=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$err=curl_error($ch);curl_close($ch);if(!is_string($body)||$code!==200||strlen($body)>MAX_BYTES)throw new RuntimeException("fetch $code $err");return $body;}
function xmlDoc(string $raw):DOMDocument{$d=new DOMDocument();$old=libxml_use_internal_errors(true);if(!$d->loadXML($raw,LIBXML_NONET|LIBXML_NOBLANKS|LIBXML_COMPACT)){libxml_clear_errors();libxml_use_internal_errors($old);throw new RuntimeException('invalid xml');}libxml_clear_errors();libxml_use_internal_errors($old);return $d;}
function xtexts(DOMDocument $d,string $xp):array{$x=new DOMXPath($d);$r=[];foreach($x->query($xp)?:[] as $n){$v=trim($n->textContent);if($v!=='')$r[]=$v;}return array_values(array_unique($r));}
function first(array $a,string $fallback=''):string{return $a[0]??$fallback;}
function severity(string $text):string{if(preg_match('/大津波警報|津波警報|特別警報|緊急地震速報|噴火警報|噴火速報/u',$text))return 'critical';if(preg_match('/警報|土砂災害警戒情報|記録的短時間大雨情報|顕著な大雨|竜巻注意情報|洪水/u',$text))return 'warning';if(preg_match('/注意報|津波注意報/u',$text))return 'advisory';return 'info';}
function category(string $text):string{if(preg_match('/津波/u',$text))return 'tsunami';if(preg_match('/地震|震度|緊急地震/u',$text))return 'earthquake';if(preg_match('/火山|噴火/u',$text))return 'volcano';if(preg_match('/台風|暴風|強風/u',$text))return 'storm';if(preg_match('/大雨|洪水|土砂|浸水/u',$text))return 'rain-flood-landslide';if(preg_match('/波浪|高潮/u',$text))return 'coastal';return 'other';}
function stopsFor(string $text):array{$map=['tsuchiura'=>['茨城','土浦','霞ヶ浦','鹿島灘'],'aizuwakamatsu'=>['福島','会津','磐梯','猪苗代'],'yamagata'=>['山形','蔵王','村山'],'tsuruoka'=>['山形','庄内','鶴岡','酒田','出羽'],'matsushima'=>['宮城','松島','東松島'],'kamaishi'=>['岩手','釜石','三陸','宮古','大船渡'],'towada'=>['青森','十和田','八甲田','奥入瀬'],'hirosaki'=>['青森','弘前','岩木'],'tazawako-senboku'=>['秋田','仙北','田沢湖','乳頭'],'sendai'=>['宮城','仙台','秋保'],'utsunomiya'=>['栃木','宇都宮','日光','中禅寺'],'narita-navrat'=>['千葉','成田','銚子','犬吠','香取']];$r=[];foreach($map as $id=>$keys){foreach($keys as $k){if(mb_strpos($text,$k)!==false){$r[]=$id;break;}}}return array_values(array_unique($r));}
function mapPoint(array $stopIds):?array{$points=['tsuchiura'=>['Tsuchiura, Ibaraki',36.07,140.20],'aizuwakamatsu'=>['Aizuwakamatsu, Fukushima',37.49,139.93],'yamagata'=>['Yamagata',38.25,140.34],'tsuruoka'=>['Tsuruoka, Yamagata',38.72,139.82],'matsushima'=>['Matsushima, Miyagi',38.37,141.06],'kamaishi'=>['Kamaishi, Iwate',39.27,141.88],'towada'=>['Towada, Aomori',40.46,140.88],'hirosaki'=>['Hirosaki, Aomori',40.60,140.46],'tazawako-senboku'=>['Lake Tazawa, Akita',39.70,140.70],'sendai'=>['Sendai, Miyagi',38.27,140.87],'utsunomiya'=>['Utsunomiya, Tochigi',36.56,139.88],'narita-navrat'=>['Narita, Chiba',35.78,140.32]];if(!$stopIds)return null;$p=$points[$stopIds[0]]??null;if(!$p)return null;return ['name'=>$p[0],'lat'=>$p[1],'lng'=>$p[2],'mapUrl'=>'https://www.google.com/maps/search/?api=1&query='.rawurlencode($p[0].', Japan')];}
function impact(array $stops,string $sev):array{if($stops)return ['status'=>'affected','text'=>'Oficiální nouzová informace se týká oblasti na plánované trase. Ověř aktuální pokyny před přesunem.','affectedStopIds'=>$stops];return ['status'=>$sev==='critical'?'watch':'not_affected','text'=>$sev==='critical'?'Závažná událost je mimo rozpoznanou trasu, ale sleduj další vývoj.':'Událost není podle dostupných oblastí přímo na plánované trase.','affectedStopIds'=>[]];}
function alert(string $id,string $title,string $summary,string $url,string $issued,string $source):array{$joined=$title.' '.$summary;$sev=severity($joined);$stops=stopsFor($joined);return ['id'=>$id,'severity'=>$sev,'category'=>category($joined),'title'=>$title,'summary'=>$summary,'issuedAt'=>$issued,'source'=>['name'=>$source,'url'=>$url],'location'=>mapPoint($stops),'itineraryImpact'=>impact($stops,$sev)];}
$alerts=[];$status=[];$seen=[];$jmaCount=0;
foreach(JMA_FEEDS as $label=>$feed){try{$doc=xmlDoc(fetchUrl($feed));$xp=new DOMXPath($doc);$entries=$xp->query("//*[local-name()='entry']");foreach($entries?:[] as $entry){if($jmaCount>=MAX_JMA_MESSAGES)break 2;$ed=new DOMDocument();$ed->appendChild($ed->importNode($entry,true));$id=first(xtexts($ed,"//*[local-name()='id']"));$title=first(xtexts($ed,"//*[local-name()='title']"));$updated=first(xtexts($ed,"//*[local-name()='updated']"));$link='';$x2=new DOMXPath($ed);foreach($x2->query("//*[local-name()='link']")?:[] as $ln){$h=$ln->attributes?->getNamedItem('href')?->nodeValue;if(is_string($h)&&str_starts_with($h,'https://')){$link=$h;break;}}if($id===''||$link===''||isset($seen[$id]))continue;$seen[$id]=1;try{$msg=xmlDoc(fetchUrl($link));$head=first(xtexts($msg,"//*[local-name()='Headline']/*[local-name()='Text']"));$areas=xtexts($msg,"//*[local-name()='Area']/*[local-name()='Name']");$kinds=xtexts($msg,"//*[local-name()='Kind']/*[local-name()='Name']");$summary=trim(implode(' / ',array_filter([$head,implode('・',array_slice($kinds,0,5)),implode('・',array_slice($areas,0,12))])));$a=alert($id,$title,$summary,$link,$updated,'Japan Meteorological Agency');if($a['severity']!=='info'||$a['itineraryImpact']['status']!=='not_affected')$alerts[]=$a;$jmaCount++;}catch(Throwable $e){}}$status[]=['name'=>'JMA '.$label,'status'=>'ok'];}catch(Throwable $e){$status[]=['name'=>'JMA '.$label,'status'=>'error'];}}
function parseRss(string $url,string $source,array &$alerts,array &$status):void{try{$d=xmlDoc(fetchUrl($url));$x=new DOMXPath($d);$items=$x->query("//*[local-name()='item']");$n=0;foreach($items?:[] as $item){if($n++>=20)break;$one=new DOMDocument();$one->appendChild($one->importNode($item,true));$title=first(xtexts($one,"//*[local-name()='title']"));$link=first(xtexts($one,"//*[local-name()='link']"),$url);$desc=first(xtexts($one,"//*[local-name()='description']"));$date=first(xtexts($one,"//*[local-name()='pubDate']"),gmdate(DATE_ATOM));$a=alert(hash('sha256',$source.$title.$link),$title,$desc,$link,$date,$source);if($a['severity']!=='info'||$a['itineraryImpact']['status']!=='not_affected')$alerts[]=$a;}$status[]=['name'=>$source,'status'=>'ok'];}catch(Throwable $e){$status[]=['name'=>$source,'status'=>'error'];}}
parseRss(FDMA_RSS,'Fire and Disaster Management Agency',$alerts,$status);parseRss(JCG_RSS,'Japan Coast Guard MICS',$alerts,$status);
$rank=['critical'=>0,'warning'=>1,'advisory'=>2,'info'=>3];usort($alerts,fn($a,$b)=>($rank[$a['severity']]<=>$rank[$b['severity']])?:strcmp($b['issuedAt'],$a['issuedAt']));$alerts=array_slice($alerts,0,50);
$payload=['schemaVersion'=>1,'kind'=>'japan-emergency-status','generatedAt'=>(new DateTimeImmutable('now',new DateTimeZone('Asia/Tokyo')))->format(DATE_ATOM),'pollIntervalSeconds'=>300,'alerts'=>$alerts,'sourceStatus'=>$status,'advisory'=>'Supplementary travel-safety channel. For life-safety decisions follow JMA, Safety Tips and local authorities directly.'];
$target=dirname(__DIR__).'/data/emergency-current.json';$lockPath=dirname(__DIR__).'/data/.emergency.lock';$lock=fopen($lockPath,'c');if(!$lock||!flock($lock,LOCK_EX))out(['error'=>'lock failed'],500);$tmp=$target.'.tmp.'.bin2hex(random_bytes(4));$encoded=json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT);if(file_put_contents($tmp,$encoded,LOCK_EX)===false||!rename($tmp,$target)){@unlink($tmp);flock($lock,LOCK_UN);fclose($lock);out(['error'=>'write failed'],500);}flock($lock,LOCK_UN);fclose($lock);out(['ok'=>true,'generatedAt'=>$payload['generatedAt'],'alerts'=>count($alerts),'critical'=>count(array_filter($alerts,fn($a)=>$a['severity']==='critical')),'warning'=>count(array_filter($alerts,fn($a)=>$a['severity']==='warning'))]);
